---
# Project information
site_name: MkDocs curriculum vitae Theme
site_url: https://paul-riviere.github.io/mkdocs-curriculum-vitae/
site_description: MkDocs curriculum vitae Theme

# Theme
theme:
  name: readthedocs

# Plugins
plugins:
  - search
